### ISSUE TITLE
no nvenc in handbrake

### ISSUE THREAD

**Issue by goffrier** [zocker-160/handbrake-nvenc-docker#9] opened 2022-02-18 11:44 UTC
i installed everything correctly, nvidia smi runs with no issues, same for the test docker container from nvidia, however your handbrake nvenc docker container doesn't work, when digging in the logs i found this: 

/var/run/s6/etc/cont-init.d/95-check-qsv.sh: 31: lspci: not found
[cont-init.d] 95-check-qsv.sh: Intel Quick Sync Video not supported: video adapter not using i915 driver.

**Comment by zocker-160** [comment] 2022-02-18 12:28
I sadly cannot reproduce this issue using the latest image, I have all options there and it works.
![Screenshot_20220218_132749](https://user-images.githubusercontent.com/36563538/154682971-c0e4c456-cc97-4732-a3ac-2d3969f2ac2b.png)

What OS are you running and which Nvidia drivers do you have installed?

**Comment by goffrier** [comment] 2022-02-18 12:47
so i don't know why it doesn't work on handbrake

**Comment by goffrier** [comment] 2022-02-18 12:49
and also i installed the drivers using this tutorial: https://forum.openmediavault.org/index.php?thread/31206-how-to-setup-nvidia-in-plex-docker-for-hardware-transcoding/ i refer to tama's tutorial

**Comment by goffrier** [comment] 2022-02-18 12:50
i can always try to run jellyfin with hw transcoding and see if it works if you need more insight

**Comment by zocker-160** [comment] 2022-02-18 12:52
Well again as I said above, only the Nvidia driver from the official installer will work.
The information about other containers working is not very useful because most of them install the Nvidia driver inside the container, which I do not do.

**Comment by goffrier** [comment] 2022-02-18 12:53
oh so i need to reinstall the drivers? okay i'll try that

**Comment by zocker-160** [comment] 2022-02-18 12:58
yes use the official Nvidia driver installer: https://www.nvidia.com/en-us/drivers/unix/

It is the recommended one for headless systems anyway.

The reason why I don't pack the Nvidia drivers inside the container (like plex or jellyfin does) is because of size and because ppl with older GPUs also need older drivers.

**Comment by goffrier** [comment] 2022-02-18 13:07
it's installed, sudo apt-get install -y nvidia-docker2 wants to remove the nvidia driver to install it's own though, should i?

**Comment by goffrier** [comment] 2022-02-18 13:10
btw after reinstalling drivers the proper way it still doesn't work

**Comment by zocker-160** [comment] 2022-02-18 13:11
are you sure you start the container with `--gpus all` ?

**Comment by goffrier** [comment] 2022-02-18 13:11
yes

**Comment by zocker-160** [comment] 2022-02-18 13:13
can you try without the two `--device` flags?
did you reboot after installing the Nvidia driver?

**Comment by goffrier** [comment] 2022-02-18 13:14
i can and yes

**Comment by goffrier** [comment] 2022-02-18 13:19
i'm gonna try to purge everything nvidia and reinstall

**Comment by goffrier** [comment] 2022-02-18 13:19
to start clean

**Comment by goffrier** [comment] 2022-02-18 13:29
okay so with the official drivers the nvidia runtime is not available in docker anymore, when i try to install it tells me to install debian drivers

**Comment by goffrier** [comment] 2022-03-02 11:50
had to clean install my whole system, now handbrake works

**Comment by zocker-160** [comment] 2022-03-02 11:53
cool glad to hear! Sorry that I could not really help you with this issue, but from my experience it is usually driver related, when it does not see the GPU.

closing

**Closed by zocker-160** 2022-03-02 11:53 UTC
